[tool.black]
line-length = 88
exclude = '''
/(
    \.venv
  | venv
  | build
  | dist
  | \.eggs
  | \.git
  | \.tox
  | \.mypy_cache
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
skip = [
  ".venv",
  "venv",
  "build",
  "dist",
  "__pycache__"
]