# deployment/cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/intelligent-accounting-assistant:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/intelligent-accounting-assistant:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'intelligent-accounting-assistant' # Name of the Cloud Run service
  - '--image'
  - 'gcr.io/$PROJECT_ID/intelligent-accounting-assistant:latest'
  - '--region'
  - 'us-central1' # Replace with your region
  # Add other Cloud Run settings like environment variables, service account, etc.
  # - '--set-env-vars'
  # - 'GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=us-central1'
images:
- 'gcr.io/$PROJECT_ID/intelligent-accounting-assistant:latest'
